import type { CommerceProduct, Tenant } from "./types.js";

export const horizonTenant: Tenant = {
  id: "tenant_horizon_creations",
  name: "Horizon Creations",
  currency: "USD",
  storefrontOrigin: "https://horizoncreations.art",
  provider: "mock",
  connectionState: "disconnected",
};

export const syntheticTenant: Tenant = {
  id: "tenant_copper_finch",
  name: "Copper Finch Studio",
  currency: "CAD",
  storefrontOrigin: "https://copper-finch.invalid",
  provider: "mock",
  connectionState: "disconnected",
};

export const initialProducts: CommerceProduct[] = [
  {
    id: "prd_horizon_heresy_journal",
    tenantId: horizonTenant.id,
    title: "Heresy Journal",
    sku: "HC-HJ-001",
    state: "available",
    fulfillmentModel: "finished_stock",
    priceCents: 7500,
    currency: "USD",
    quantity: 1,
    publicCheckout: false,
    source: "site-v2/catalog.mjs#products[0]",
    leadTime: null,
    providerProductId: null,
    version: 1,
  },
  {
    id: "prd_horizon_everyday_carry_pouch",
    tenantId: horizonTenant.id,
    title: "Everyday Carry Pouch",
    sku: "HC-ECP-001",
    state: "made_to_order",
    fulfillmentModel: "made_to_order",
    priceCents: 8500,
    currency: "USD",
    quantity: null,
    publicCheckout: false,
    source: "site-v2/catalog.mjs#products[1]",
    leadTime: "REQUIRED_AT_CONNECTION_GATE",
    providerProductId: null,
    version: 1,
  },
  ...[
    ["banzai_journal", "Banzai Journal", "HC-BJ-001"],
    ["turtles_journal", "Turtles Journal", "HC-TJ-001"],
    ["green_mushroom_journal", "Green Mushroom Journal", "HC-GMJ-001"],
  ].map(([slug, title, sku]) => ({
    id: `prd_horizon_${slug}`,
    tenantId: horizonTenant.id,
    title,
    sku,
    state: "sold" as const,
    fulfillmentModel: "gallery_only" as const,
    priceCents: 0,
    currency: "USD",
    quantity: 0,
    publicCheckout: false as const,
    source: "site-v2/catalog.mjs#soldPieces",
    leadTime: null,
    providerProductId: null,
    version: 1,
  })),
  {
    id: "prd_copper_finch_print",
    tenantId: syntheticTenant.id,
    title: "Field Note Print",
    sku: "CF-P-001",
    state: "available",
    fulfillmentModel: "finished_stock",
    priceCents: 2400,
    currency: "CAD",
    quantity: 8,
    publicCheckout: false,
    source: "fixtures/copper-finch",
    leadTime: null,
    providerProductId: null,
    version: 1,
  },
  {
    id: "prd_copper_finch_case",
    tenantId: syntheticTenant.id,
    title: "Made-to-Order Case",
    sku: "CF-C-002",
    state: "made_to_order",
    fulfillmentModel: "made_to_order",
    priceCents: 6500,
    currency: "CAD",
    quantity: null,
    publicCheckout: false,
    source: "fixtures/copper-finch",
    leadTime: "10 business days",
    providerProductId: null,
    version: 1,
  },
];
